---
- hosts: all
  become: yes

  # This used to clean up playbook/organize easier
  vars_files:
    - vars.yml

  # Pre tasks are run before main tasks
  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

  # handlers are tasks you run at end of play (if task notifies and makes change)
  # Add option 'notify: restart apache'
  handlers: 
    - name: restart apache
      service: name=apache2 state=restarted
tasks:
  - name: Get software for repo mgmt
    apt: 
      state: present
      name:
        - python3-apt
        - python3-pycurl

  - name: install apache, mysql....
    apt: 
      state: present
      name:
        - acl
        - git
        - curl
        - unzip
        - sendmail
        - apache2
        - php7.4-common
        - php7.4-cli
        - php7.4-dev
        - php7.4-gd
        - php7.4-curl
        - php7.4-jso
        - php7.4-opcache
        - php7.4-xml
        - php7.4-mbstring
        - php7.4-pdo
        - php7.4-mysql
        - libpcre3-dev
        - libapache2-mod-php7.4
        - python3-mysqldb
        - mysql-server

  - name: disable firewall
    service: name=ufw state=stopped

  - name: start apache, mysql, php
    service: "name={{ item }} state=started enabled=yes"
    with_items:
      - apache2
      - mysql

  - name: enable apache rewrite module (for drupal)
    apache2_module: name=rewrite state=present
    notify: restart apache

  - name: add apache virtualhost
    template:
      src: "templates/drupal.test.conf.j2"
      dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
      owner: root 
      group: root
      mode: 0644
    notify: restart apache


  - name: Enable drupal
    command: >
      a2ensite {{ domain }}.test
      creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
    notify: restart apache
  
  - name: disable default apache site
    command: >
      a2dissite 000-default
      removes=/etc/apache2/sites-enabled/000-default.conf
    notify: restart apache
